### ISSUE TITLE
How to create a denylist like badbits

### ISSUE THREAD

**Issue by chilcano** [ipfs-shipyard/nopfs#15]
Hi there!
Sorry if this is not the right place to ask about this.

I have a simple Python-based HTTP proxy created to block incoming request if the CID included in the request is in the badbits denylist  (https://badbits.dwebops.pub/denylist.json). 

The problem is that I don't know how to calculate the hash/multihash.
The indications in Badbits to calculate the hash is not enough for me.

> The [Bad Bits Denylist](https://badbits.dwebops.pub/badbits.deny) is a list of hashed [CIDs](https://docs.ipfs.io/concepts/content-addressing/) that have been flagged for various reasons (copyright violation, malware, etc). Each entry is the hex-encoded result of applying SHA2_256 to a <base32-encoded-cidv1-string>/<optional_path> string. This format is legacy and we are moving to support double-hashed mulihashes instead.

Please, could you help me with that?
Regards.

**Comment by hsanjuan** [comment]
The line in the list is the result of `sha256sum(<cid_v1>/)`. Any CIDv0 needs to be converted to CIDv1 and then hashed with a slash at the end.
