### ISSUE TITLE
how to use nopfs?

### ISSUE THREAD

**Issue by monperrus** [ipfs-shipyard/nopfs#2]
Hi, nopfs looks perfect for integrating bad bits. However, it's unclear to me how to install and use nopfs.

Thanks!

**Comment by hsanjuan** [comment]
Hello,

I'm currently waiting for a stable release of [Kubo to include the necessary changes](https://github.com/ipfs/kubo/issues/9839#issuecomment-1542692493). This will allow to align dependencies and provide either a pre-built plugin or at least an streamlined way of building it.

This can currently be done with master etc. by aligning dependencies manually with current Kubo master.

 Other than that, nopfs provides a [Go Blocker implementation](https://pkg.go.dev/github.com/ipfs-shipyard/nopfs#NewBlocker) that can be used to parse the compact list format and ask questions (i.e IsCidBlocked). And the Kubo plugin is built using [wrappers around NameSystem, BlockService and Resolver types](https://pkg.go.dev/github.com/ipfs-shipyard/nopfs/ipfs), that call the Blocker methods, which could of course also be used when building something custom.

All in all, as soon as I can depend on a stable release of Kubo & co. there code will be made to work as easy as possible with upstream. Leaving this open until then.

**Comment by monperrus** [comment]
OK, thanks Hector!

**Comment by hsanjuan** [comment]
@monperrus can you give a try to this? https://github.com/ipfs-shipyard/nopfs/releases/tag/nopfs-kubo-plugin%2Fv0.21.0-rc1.3
